### ISSUE TITLE
Outdated readme 

### ISSUE THREAD

**Issue by SnoopyDevelops** [langchain-ai/chat-langchain#136]
There is no `requirements.txt` file

**Comment by sriharigr** [comment]
Yes, I was looking for the same

**Comment by Hemapriya17** [comment]
requirements.txt file missing

**Comment by kshkaran2k** [comment]
Yes, I am also looking for the same.
Has anyone tried with any previous version of the repo?

**Comment by JoyLinWQ** [comment]
@SnoopyDevelops @sriharigr @Hemapriya17 @kshkaran2k 

This doesn't use `requirements.txt`. 
It uses the `pyproject.toml` file and `poetry install`.
https://github.com/langchain-ai/chat-langchain/blob/master/pyproject.toml

You can start with creating a virtual environment below:
`conda create --name chat-langchain python=3.10` then `conda activate chat-langchain` and follow with the `poetry install` in their docs.
