### ISSUE TITLE
[Question] How to set RECORD_MANAGER_DB_URL

### ISSUE THREAD

**Issue by gyliu513** [langchain-ai/chat-langchain#192]
Do I need to set up a DB myself or does there are any existing free DB that I can use for this demo?

**Comment by JoyLinWQ** [comment]
@gyliu513 , i tried following this example here using Supabase.
https://blog.langchain.dev/building-chat-langchain-2/

**Comment by gyliu513** [comment]
It also works with sqlite, thanks @JoyLinWQ

**Comment by kientv** [comment]
I'm using: mysql  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

And error appear:

>   File "/home/chat-langchain/venv/lib/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 6497, in visit_create_table
>     raise exc.CompileError(
> sqlalchemy.exc.CompileError: (in table 'upsertion_record', column 'uuid'): VARCHAR requires a length on dialect mysql
>

**Comment by JoyLinWQ** [comment]
> > @gyliu513 , i tried following this example here using Supabase. https://blog.langchain.dev/building-chat-langchain-2/
> 
> @JoyLinWQ : I created a Supabase and I set `record_manager_db_url = "https://<id>.supabase.co".` I got an error after loading documents completed.
> 
> error: NosSuchModuleError: Can't load plugin: sqlalchemy.dialects.https
> 
> The db_url I set is correct format?

@lam0620 , the db_url looks correct. The error is coming from sqlalchemy, you may want to look into that instead?
