### ISSUE TITLE
chat.langchain.com is not working, it keeps loading, even the website we created on top of it also not working

### ISSUE THREAD

**Issue by Fariz-fx** [langchain-ai/chat-langchain#214]
When i visit [chat-langchain website](https://chat.langchain.com/) it will provide result quickly however not its working its keep loading refer below image
![image](https://github.com/langchain-ai/chat-langchain/assets/34375965/371455ea-c2f5-4f10-a07d-34e1db8ca9ef)

3 days back it worked fine, now not sure why it's not woking. 
Expected behaviour: For given prompt it should load data quicker

I can also see Update index action is failing i believe issue is with weaviate

**Comment by ddm1293** [comment]
It worked fine yesterday, I think it is because of the updates released on the dev day.

**Comment by hinthornw** [comment]
Should be working now. There were a couple incidents from llm and embedding provider outages
