### ISSUE TITLE
Getting output twice please someone help me. Please check the screenshot of answer. Thanks to all

### ISSUE THREAD

**Issue by MuhammadNaeem42** [langchain-ai/chat-langchain#299]
![Screenshot from 2024-04-06 03-28-40](https://github.com/langchain-ai/chat-langchain/assets/106573678/877dff8e-f119-4438-bd68-79ec12eb50a9)

**Comment by iiitmahesh** [comment]
Same issue here. Downgrade version langchain, it will solve the problems for the time being. 

Core issue in ChatWindow.tsx
import { RemoteRunnable } from "langchain/runnables/remote";
import { applyPatch } from "@langchain/core/utils/json_patch";
(working versions)
`langchain@0.1.26`
`@langchain/core@0.1.44`

**Comment by MuhammadNaeem42** [comment]
Thanks @iiitmahesh

**Comment by luca-git** [comment]
Won't compile using
import { RemoteRunnable } from "langchain/runnables/remote";

**Comment by luca-git** [comment]
thanks! @iiitmahesh langchain 0.1.16 langchain-core 0.1.44 and applying this: https://github.com/langchain-ai/chat-langchain/pull/301/files/87f09408e685b76e5a146184a81a84f96cfcc603  finally worked for me!
