### ISSUE TITLE
Why the answer string show duplicated words on front end?

### ISSUE THREAD

**Issue by jinjunzh** [langchain-ai/chat-langchain#300]
Tried to set up chat-langchain locally , but it looks answers in browser has below problems which show duplicated words, but debug backtrace from smith , it looks response works fine, why this issue happen?
..........
Answer
<<||useruser||>>
CanCan you you provide provide me me with with instructions instructions on on how how to to.........

**Comment by iiitmahesh** [comment]
@jinjunzh Check this #299

**Comment by jinjunzh** [comment]
This solution [#299](https://github.com/langchain-ai/chat-langchain/issues/299) looks doesn't work for me, anything else missing? @iiitmahesh 
---------------------
diff --git a/frontend/app/components/ChatWindow.tsx b/frontend/app/components/ChatWindow.tsx
index f4aa4dd..2fb0a98 100644
--- a/frontend/app/components/ChatWindow.tsx
+++ b/frontend/app/components/ChatWindow.tsx
@@ -2,7 +2,7 @@

 import React, { useEffect, useRef, useState } from "react";
 import { useSearchParams } from "next/navigation";
-import { RemoteRunnable } from "@langchain/core/runnables/remote";
**+import { RemoteRunnable } from "langchain/runnables/remote";
 import { applyPatch } from "@langchain/core/utils/json_patch";**

---------------------
diff --git a/frontend/package.json b/frontend/package.json
index 5e562b7..50766ce 100644
--- a/frontend/package.json
+++ b/frontend/package.json
@@ -15,7 +15,7 @@
     "@chakra-ui/react": "^2.8.1",
     "@emotion/react": "^11.11.1",
     "@emotion/styled": "^11.11.0",
-    "@langchain/core": "^0.1.27",
**+    "@langchain/core": "0.1.44",**
     "@types/dompurify": "^3.0.5",
     "@types/marked": "^5.0.1",
     "@types/node": "20.4.9",
@@ -29,6 +29,7 @@
     "framer-motion": "^10.16.4",
     "graphql": "^16.8.1",
     "highlight.js": "^11.8.0",
**+    "langchain": "0.1.26",**
     "langsmith": "^0.0.41",
     "marked": "^7.0.2",
     "next": "13.5.4",

**Comment by luca-git** [comment]
Which would be the python langchain version needed?

**Comment by jinjunzh** [comment]
python 3.10
Langchain version: 0.1.16

**Comment by jinjunzh** [comment]
> python 3.10
> Langchain version: 0.1.16



> 需要哪个 python langchain 版本？

python 3.10
Langchain version: 0.1.16

**Comment by jinjunzh** [comment]
> 需要哪个 python langchain 版本？

python 3.10
Langchain version: 0.1.16

**Comment by jinjunzh** [comment]
> Which would be the python langchain version needed?

python 3.10
Langchain version: 0.1.16
