### ISSUE TITLE
Windows - powershell errors after starting

### ISSUE THREAD

**Issue by shanumas** [langchain-ai/chat-langchain#334]
![image](https://github.com/langchain-ai/chat-langchain/assets/34864140/6d72793a-6de5-4311-b34f-766768d174ab)

![image](https://github.com/langchain-ai/chat-langchain/assets/34864140/83fd765a-78de-4b8d-98a2-c5711bc68fe5)

**Comment by vbarda** [comment]
@shanumas we do not plan to support windows for the observable future, but will let you know if this changes
