### ISSUE TITLE
https://chat.langchain.com/ is not working

### ISSUE THREAD

**Issue by AbhijitKuma** [langchain-ai/chat-langchain#360]
https://chat.langchain.com/ is not working for last 2 days, looks like there is invalid certificate issue. I get below message. Please fix it. This is quite helpful. 
![image](https://github.com/user-attachments/assets/0bfbdd0b-cf74-40a8-805b-3b61d7cbec50)
![image](https://github.com/user-attachments/assets/7de034e7-5371-4963-9665-0341ce2fbc39)

**Comment by vbarda** [comment]
i just tried and it's working fine for me -- can you double-check?

**Comment by AbhijitKuma** [comment]
Yes. Its working now. Thanks a lot!
