### ISSUE TITLE
How to integrate ConversationalRetrievalChain with Custom Agent returning the source documents

### ISSUE THREAD

**Issue by Rajatag27** [langchain-ai/chat-langchain#38]
I am using the latest version of langchain to build chat with data application.

I want to use Agent with ConversationalRetrievalChain which can return source documents. Getting following error

**My code is:**
qa_ret = ConversationalRetrievalChain.from_llm(ChatOpenAI(temperature=0), vectorstore.as_retriever(), qa_prompt=prompt, return_source_documents=True)

tools = [
    Tool(
        name = "Docstore",
        func=qa_ret.run,
        description="useful for when you need to answer questions about document",
        return_direct=True
    ),
]

agent = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=False)

agent.run("What is Apple?")

**Error:**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[51], line 1
----> 1 response = agent.run("What is Apple?")

~/.conda/envs/langChain2/lib/python3.10/site-packages/langchain/chains/base.py:213), in Chain.run(self, *args, **kwargs)
    211     if len(args) != 1:
    212         raise ValueError("`run` supports only one positional argument.")
--> 213     return self(args[0])[self.output_keys[0]]
    215 if kwargs and not args:
    216     return self(kwargs)[self.output_keys[0]]

~/.conda/envs/langChain2/lib/python3.10/site-packages/langchain/chains/base.py:116), in Chain.__call__(self, inputs, return_only_outputs)
    114 except (KeyboardInterrupt, Exception) as e:
    115     self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116     raise e
    117 self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118 return self.prep_outputs(inputs, outputs, return_only_outputs)

~/.conda/envs/langChain2/lib/python3.10/site-packages/langchain/chains/base.py:113), in Chain.__call__(self, inputs, return_only_outputs)
    107 self.callback_manager.on_chain_start(
    108     {"name": self.__class__.__name__},
    109     inputs,
    110     verbose=self.verbose,
    111 )
...
    208     )
    210 if args and not kwargs:
    211     if len(args) != 1:

**ValueError: `run` not supported when there is not exactly one output key. Got ['answer', 'source_documents'].**

**Comment by touhi99** [comment]
Having the same problem

**Comment by fsukhenko** [comment]
So all Tools need a run function defined that takes a string and ConversationalRetrievalChain does not have that. It instead is called with the a base function on the class with a dictionary object passed.

Assuming you followed the example from here https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html
and have the following already defined somewhere in your code:
`qa = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0), vectorstore.as_retriever(), memory=memory)`

in your tool definition do this:
`
Tool (name='whatever the name',
	func = lambda query: qa({"question": query}),
	description = 'the description for this tool'
	)
`

**Comment by MarkEdmondson1234** [comment]
This has happened to me a few times and I always end up here, the easiest work around is to not use run:

```
...
result = qa({"question": "do you know anything about coor?", 
             "chat_history": [
        ("What is the date Australia was founded.", "Australia was founded in 1901.")]})
```

e.g don't do:

```
result = qa.run({"question": "do you know anything about coor?", 
             "chat_history": [
        ("What is the date Australia was founded.", "Australia was founded in 1901.")]})
# raise ValueError(
ValueError: `run` not supported when there is not exactly one output key. Got ['answer', 'source_documents'].
```

**Comment by ChekeLee** [comment]
langchain version 0.0.188
after initializing the memory,
```memory = ConversationBufferWindowMemory(k=3,memory_key = "chat_history",return_messages=True)```
set 
```
memory.input_key="question"
memory.output_key="answer"
```
worked for me.
As if you don't set output_key, 'memory' will confirm the length output should be 1. Set the output_key explicitly, it will be used for getting the output.
