### ISSUE TITLE
Error when pulling prompts from langsmith

### ISSUE THREAD

**Issue by andyvauliln** [langchain-ai/chat-langchain#396]
Hi is this prompts public? hub.pull("chat-langchain-research-plan-prompt"). I have error when i starting project related to prompts

('404 Client Error: Not Found for url: https://api.smith.langchain.com/commits/chat-langchain-router-prompt/latest'

How i can get them?

**Comment by vbarda** [comment]
Fixed in #399  - thanks for reporting!
